In [2]:
import pandas as pd

df = pd.read_csv("Metro_Interstate_Traffic_Volume.csv")
print(df.shape)   # (jumlah baris, jumlah kolom)
df.head()

(48204, 9)

,traffic_volume,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time
0,5545,NaN,288.28,0.0,0.0,40,Clouds,scattered clouds,02-10-2012 09:00
1,4516,NaN,289.36,0.0,0.0,75,Clouds,broken clouds,02-10-2012 10:00
2,4767,NaN,289.58,0.0,0.0,90,Clouds,overcast clouds,02-10-2012 11:00
3,5026,NaN,290.13,0.0,0.0,90,Clouds,overcast clouds,02-10-2012 12:00
4,4918,NaN,291.14,0.0,0.0,75,Clouds,broken clouds,02-10-2012 13:00

In [3]:
df.info()                 # tipe data setiap kolom
df.isna().sum()           # jumlah data kosong per kolom
df.duplicated().sum()     # jumlah baris duplikat

<class 'pandas.DataFrame'>
RangeIndex: 48204 entries, 0 to 48203
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   traffic_volume       48204 non-null  int64
 1   holiday              61 non-null     str
 2   temp                 48204 non-null  float64
 3   rain_1h              48204 non-null  float64
 4   snow_1h              48204 non-null  float64
 5   clouds_all           48204 non-null  int64
 6   weather_main         48204 non-null  str
 7   weather_description  48204 non-null  str
 8   date_time            48204 non-null  str
dtypes: float64(3), int64(2), str(4)
memory usage: 4.8 MB

np.int64(17)

In [7]:
df = pd.read_csv('Metro_Interstate_Traffic_Volume.csv')
#memuat dataset
df['date_time'] = pd.to_datetime(df['date_time'], format = 'mixed')
#mengubah kolom date time dari string ke tipe date time, format ='mixed'
#agar dapat menebak da menyesuaikan format tanggal / waktu yang bervariasi
print(df.dtypes)
#nge print dataset yang sudah diubah

traffic_volume                  int64
holiday                           str
temp                          float64
rain_1h                       float64
snow_1h                       float64
clouds_all                      int64
weather_main                      str
weather_description               str
date_time              datetime64[us]
dtype: object

In [12]:
kolom_list = {'traffic_volume', 'temp', 'clouds_all' }
#3 kolom yang akan dianalisis
ringkasan_data = []
#membuat fungsi atau ringkasan perhitungan untuk setiap data
for col in kolom_list:
    s = df[col]
    #ukuran pemusatan
    mean_val = s.mean()
    median_val = s.median()
    mode_val = s.mode()[0]
    #ukuran penyebaran
    min_val = s.min()
    max_val = s.max()
    jangkauan = max_val - min_val
    var_val = s.var()
    std_val = s.std()

    q1 = s.quantile(0.25)
    q3 = s.quantile(0.75)
    iqr = q3 - q1

    ringkasan_data.append({
        'Kolom': col,
        'Mean': mean_val,
        'Median': median_val,
        'Modus': mode_val,
        'Min': min_val,
        'Max': max_val,
        'Jangkauan': jangkauan,
        'Varians': var_val,
        'Simpangan Baku': std_val,
        'Q1': q1,
        'Q3': q3,
        'IQR': iqr
    
    })

tabel_ringkasan = pd.DataFrame(ringkasan_data)
display(tabel_ringkasan)

,Kolom,Mean,Median,Modus,Min,Max,Jangkauan,Varians,Simpangan Baku,Q1,Q3,IQR
0,traffic_volume,3259.818355,3380.00,353.00,0.0,7280.00,7280.00,3.947615e+06,1986.860670,1193.00,4933.000,3740.000
1,clouds_all,49.362231,64.00,90.00,0.0,100.00,100.00,1.522229e+03,39.015750,1.00,90.000,89.000
2,temp,281.205870,282.45,274.15,0.0,310.07,310.07,1.779084e+02,13.338232,272.16,291.806,19.646